import { Incident, Vehicle } from '../types/api';

export const mockIncidents: Incident[] = [
  {
    id: 'inc-001',
    caseNumber: 'EOC-9021',
    status: 'SUBMITTED',
    priority: 'CRITICAL',
    chiefComplaint: 'Multi-Vehicle Collision',
    locationName: 'Highway A12 - Exit 4',
    subCounty: 'Westlands',
    lat: -1.2655,
    lng: 36.8010,
    massCasualty: true,
    callerName: 'John Doe',
    callerPhone: '0700000000',
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'inc-002',
    caseNumber: 'EOC-9022',
    status: 'DISPATCH_HANDLING',
    priority: 'HIGH',
    chiefComplaint: 'Structure Fire - Residential',
    locationName: 'South B, Mukuru',
    subCounty: 'Starehe',
    lat: -1.3122,
    lng: 36.8340,
    massCasualty: false,
    callerName: 'Jane Smith',
    callerPhone: '0711111111',
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'inc-003',
    caseNumber: 'EOC-9023',
    status: 'DISPATCHED',
    priority: 'HIGH',
    chiefComplaint: 'Cardiac Arrest',
    locationName: 'Lavington Mall',
    subCounty: 'Dagoretti North',
    lat: -1.2780,
    lng: 36.7645,
    massCasualty: false,
    callerName: 'Security Desk',
    callerPhone: '0722222222',
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'inc-004',
    caseNumber: 'EOC-9024',
    status: 'RESOLVED',
    priority: 'LOW',
    chiefComplaint: 'Minor Injury - Fall',
    locationName: 'Central Park',
    subCounty: 'CBD',
    lat: -1.2865,
    lng: 36.8172,
    massCasualty: false,
    callerName: 'Peter Park',
    callerPhone: '0733333333',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  }
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-001',
    registrationNumber: 'KCA 123X',
    status: 'READY',
    agencyId: 'agency-1',
    lastLat: -1.2921,
    lastLng: 36.8219,
    imei: '864321045678901',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'veh-002',
    registrationNumber: 'KCB 456Y',
    status: 'BUSY',
    agencyId: 'agency-1',
    lastLat: -1.3000,
    lastLng: 36.8100,
    imei: '864321045678902',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'veh-003',
    registrationNumber: 'KCC 789Z',
    status: 'MAINTENANCE',
    agencyId: 'agency-1',
    lastLat: -1.2800,
    lastLng: 36.8300,
    imei: '864321045678903',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const mockQueueData = mockIncidents.filter(inc => inc.status !== 'RESOLVED');
